### ISSUE TITLE
there is a problem about running this program in mac

### ISSUE THREAD

**Issue by cxl4444** [Roman-UCSD/BasicATLAS#1]

**Comment by cxl4444** [comment]
Hello,

When I run this program in Mac, the files in the /bin/ cannot be operated. Is it because the .exe files cannot run in Mac?

The following are the warnings:

(base) cxl:BasicATLAS-master cxl$ python test.py 
File bin/dfsortp.exe is missing
File bin/dfsynthe.exe is missing
File bin/kappa9.exe is missing
File bin/kapreadts.exe is missing
File bin/separatedf.exe is missing
File bin/xnfdf.exe is missing
File data/dfsynthe_files/diatomicsdf.bin is missing
File data/dfsynthe_files/h2olinesdf.bin is missing
File data/dfsynthe_files/highlinesdf.bin is missing
File data/dfsynthe_files/lowlinesdf.bin is missing
File data/dfsynthe_files/nltelinesdf.bin is missing
File data/dfsynthe_files/tiolinesdf.bin is missing

I downloaded all of the .exe files stored in the /bin/.

Best regards.

**Comment by Roman-UCSD** [comment]
Hi!

My apologies, somehow GitHub did not notify me of this and I did not see the issue until now.
 
 The executable files in the bin/ directory are not downloaded, but compiled from source with the compile.com script. In turn, the source code is downloaded using the download.com script. You must run download.com followed by compile.com before the package can be used.

Note that ".exe" merely stands for "executable" and has no relation to Windows .exe files. The compilation script should be producing executable files compatible with your operating system.
 
 Please also refer to Mac-specific instructions on the front page on setting up the necessary compilers.
  
  Roman
